{{- if .Values.kcm.installTemplates }}
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: {{ .Values.kcm.kof.repo.name }}
  namespace: {{ .Values.kcm.namespace }}
  labels:
    k0rdent.mirantis.com/managed: "true"
  annotations:
    # To avoid `HelmRepository not found` in `MultiClusterService/ClusterDeployment`:
    helm.sh/hook: pre-install,pre-upgrade
spec:
{{ .Values.kcm.kof.repo | toYaml | indent 2 }}
{{- end }}
