{{- if .Values.kcm.installTemplates }}
  {{- range $name := list "operators" "collectors" "istio" "storage" }}
---
apiVersion: k0rdent.mirantis.com/v1alpha1
kind: ServiceTemplate
metadata:
  name: kof-{{ $name }}-{{ $.Chart.Version | replace "." "-" }}
  namespace: {{ $.Values.kcm.namespace }}
spec:
  helm:
    chartSpec:
      chart: kof-{{ $name }}
      version: {{ $.Chart.Version | quote }}
      interval: 10m0s
      sourceRef:
        kind: HelmRepository
        name: {{ $.Values.kcm.kof.repo.name }}
  {{- end }}
{{- end }}
