{{- if .Values.promxy.ingress.enabled }}
{{- $path := .Values.promxy.ingress.path -}}
{{- $pathType := .Values.promxy.ingress.pathType -}}
{{- $servicePort := .Values.promxy.service.servicePort -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
{{- if .Values.promxy.ingress.annotations }}
  annotations:
{{ toYaml .Values.promxy.ingress.annotations | indent 4 }}
{{- end }}
  labels:
  {{- include "promxy.labels" . | nindent 4 }}
  {{ with .Values.promxy.ingress.extraLabels }}
{{ toYaml . | indent 4 }}
  {{ end }}
  name: {{ template "promxy.fullname" . }}-promxy
  namespace: {{ .Release.Namespace }}
spec:
  ingressClassName: {{ .Values.promxy.ingress.ingressClassName }}
  rules:
  {{- $serviceName := include "promxy.fullname" . }}
  {{- range .Values.promxy.ingress.hosts }}
  - host: {{ . | quote }}
    http:
      paths:
        - path: {{ $path }}
          pathType: {{ $pathType }}
          backend:
            service:
              name: {{ $serviceName }}
              port:
                number: {{ $servicePort }}
  {{- end -}}
{{- if .Values.promxy.ingress.tls }}
  tls:
{{ toYaml .Values.promxy.ingress.tls | indent 4 }}
{{- end -}}
{{- end -}}
