{{- if .Values.promxy.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "promxy.fullname" . }}-promxy
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "promxy.labels" . | nindent 4 }}
    {{- if .Values.promxy.extraLabels}}
    {{ toYaml .Values.promxy.extraLabels | nindent 4 }}
    {{- end}}
  {{- with .Values.promxy.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.promxy.replicaCount }}
  {{- if (.Values.promxy.deployment | default dict).strategy }}
  strategy:
    {{- toYaml .Values.promxy.deployment.strategy | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "promxy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "promxy.selectorLabels" . | nindent 8 }}
        {{- if .Values.promxy.extraLabels}}
        {{ toYaml .Values.promxy.extraLabels | nindent 8 }}
        {{- end}}
      annotations:
        {{- range $key, $value := .Values.promxy.podAnnotations }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
    spec:
    {{- with .Values.promxy.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "promxy.serviceAccountName" . }}
    {{- if .Values.promxy.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.promxy.nodeSelector | indent 8 }}
    {{- end }}
    {{- with .Values.promxy.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- if .Values.promxy.affinity }}
      affinity:
{{ toYaml .Values.promxy.affinity | indent 8 }}
    {{- end }}
      containers:
      - name: promxy
        args:
        - "--config=/etc/promxy/config.yaml"
        - "--web.enable-lifecycle"
        {{- range $key, $value := .Values.promxy.extraArgs }}
        - "--{{ $key }}={{ $value }}"
        {{- end }}
          {{- if .Values.promxy.env }}
        env:
{{ toYaml .Values.promxy.env | indent 10}}
        {{- end }}
        command:
        - "/bin/promxy"
        image: "{{ .Values.promxy.image.repository }}:{{ default .Chart.AppVersion .Values.promxy.image.tag }}"
        imagePullPolicy: {{ .Values.promxy.image.pullPolicy }}
        livenessProbe:
          failureThreshold: 6
          httpGet:
            path: /-/healthy
            port: http
            scheme: HTTP
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 3
        readinessProbe:
          failureThreshold: 120
          httpGet:
            path: /-/ready
            port: http
            scheme: HTTP
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 3
        ports:
        - containerPort: 8082
          name: http
        volumeMounts:
        - mountPath: "/etc/promxy/"
          name: config
          readOnly: true
        resources:
          {{- toYaml .Values.promxy.resources | nindent 12 }}
      # container to reload configs on configmap change
      - name: promxy-server-configmap-reload
        args:
        - "--volume-dir=/etc/promxy"
        - "--webhook-url=http://localhost:8082/-/reload"
        image: jimmidyson/configmap-reload:v0.5.0
        volumeMounts:
        - mountPath: "/etc/promxy/"
          name: config
          readOnly: true
        resources: 
          {{- toYaml .Values.promxy.configmapReload.resources | nindent 12 }}
      volumes:
      - name: config
        secret:
          secretName: {{ include "promxy.secretname" .}}
{{- end }}
