{{- if .Values.promxy.operator.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: promxy-operator
  name: {{ include "promxy.fullname" . }}-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "promxy.fullname" . }}-operator
subjects:
- kind: ServiceAccount
  name: {{ include "promxy.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
