apiVersion: v2
name: kof-mothership
description: A Helm chart that deploys Grafana, Promxy, and VictoriaMetrics.
version: "0.1.0"
appVersion: "0.1.0"
dependencies:
  - name: grafana-operator
    version: v5.13.0
    repository: "oci://ghcr.io/grafana/helm-charts"
    condition: grafana.enabled
  - name: victoria-metrics-operator
    version: "0.36.*"
    repository: "https://victoriametrics.github.io/helm-charts/"
    condition: victoria-metrics-operator.enabled
  - name: cluster-api-visualizer
    version: "1.4.*"
    repository: "https://jont828.github.io/cluster-api-visualizer/charts"
    condition: cluster-api-visualizer.enabled
  - name: sveltos-dashboard
    version: "0.44.*"
    repository: "https://projectsveltos.github.io/dashboard-helm-chart"
    condition: sveltos-dashboard.enabled
