apiVersion: kof.k0rdent.mirantis.com/v1alpha1
kind: PromxyServerGroup
metadata:
  labels:
    app.kubernetes.io/name: kof-operator
    app.kubernetes.io/managed-by: kustomize
    k0rdent.mirantis.com/promxy-secret-name: promxy-secret
  name: promxyservergroup-sample
spec:
  cluster_name: storage0
  targets:
    - "vmauth.storage0.example.net:443"
  path_prefix: "/vm/select/0/prometheus/"
  scheme: https
  http_client:
    dial_timeout: "1s"
    tls_config:
      insecure_skip_verify: true
    basic_auth:
      credentials_secret_name: "storage-vmuser-credentials"
      username_key: "username"
      password_key: "password"
