apiVersion: v2
name: kof-operators
description: A Helm chart that deploys opentelemetry-operator and prometheus CRDs
version: "0.2.1"
appVersion: "0.2.1"
dependencies:
  - name: opentelemetry-operator
    version: "0.84.*"
    repository: "https://open-telemetry.github.io/opentelemetry-helm-charts"
    condition: opentelemetry-operator.enabled
  - name: prometheus-operator-crds
    version: "15.0.*"
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus-operator-crds.enabled
