apiVersion: v2
name: kof-storage
description: A Helm chart that deploys Grafana, and VictoriaMetrics.
version: "0.2.1"
appVersion: "0.2.1"
dependencies:
  - name: grafana-operator
    version: v5.15.1
    repository: "oci://ghcr.io/grafana/helm-charts"
    condition: grafana.enabled
  - name: victoria-metrics-operator
    version: "0.40.*"
    repository: "https://victoriametrics.github.io/helm-charts/"
    condition: victoria-metrics-operator.enabled
  - name: victoria-logs-single
    version: "0.8.*"
    repository: https://victoriametrics.github.io/helm-charts/
    condition: victoria-logs-single.enabled
  - name: external-dns
    version: "1.15.*"
    repository: "https://kubernetes-sigs.github.io/external-dns/"
    condition: external-dns.enabled
  - name: jaeger-operator
    version: "2.50.*"
    repository: https://jaegertracing.github.io/helm-charts
    condition: jaeger-operator.enabled
