{{- if .Values.kcm.installTemplates }}
# https://github.com/k0rdent/catalog/blob/main/charts/k0rdent-catalog/k0rdent-catalog-1.0.0/templates/helm-repository.yaml
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: k0rdent-catalog
  namespace: {{ .Values.kcm.namespace }}
  labels:
    k0rdent.mirantis.com/managed: "true"
  annotations:
    helm.sh/hook: pre-install
    helm.sh/resource-policy: keep
spec:
  type: oci
  url: oci://ghcr.io/k0rdent/catalog/charts
{{- end }}
