apiVersion: v2
name: kof-collectors
description: A Helm chart that deploys OpenTelemetryCollector resources
version: "0.2.1"
appVersion: "0.2.1"
dependencies:
  - name: prometheus-node-exporter
    version: "4.39.*"
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus-node-exporter.enabled
  - name: kube-state-metrics
    version: "5.25.*"
    repository: https://prometheus-community.github.io/helm-charts
    condition: kube-state-metrics.enabled
  - name: opencost
    version: "1.42.*"
    repository: https://opencost.github.io/opencost-helm-chart
    condition: opencost.enabled
