{{- if .Values.collectors.enabled }}
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: {{ .Release.Name }}-node-exporter
  namespace: {{ .Release.Namespace }}
spec:
  mode: daemonset
  {{- if .Values.collectors.node.run_as_root }}
  securityContext:
    runAsUser: 0
  {{- end }}
  tolerations:
    - key: "node-role.kubernetes.io/master"
      operator: "Exists"
      effect: "NoSchedule"
  volumes:
    - name: varlog
      hostPath:
        path: /var/log
  volumeMounts:
    - name: varlog
      mountPath: /var/log
      readOnly: true
  serviceAccount: "{{ .Release.Name }}-k8s-cluster-collector"
  targetAllocator:
    image: "ghcr.io/open-telemetry/opentelemetry-operator/target-allocator:main"
    enabled: true
    serviceAccount: "{{ .Release.Name }}-node-exporter-ta"
    allocationStrategy: per-node
    prometheusCR:
      enabled: true
      podMonitorSelector: {}
      scrapeInterval: 10s
      serviceMonitorSelector: {}
  {{- with .Values.collectors.node.env }}
  env: {{ toYaml . | nindent 4 }}
  {{- end }}
  config:

    {{- $receivers := include "node_receivers" (dict "Values" .Values) | fromYaml }}
    receivers: {{ .Values.collectors.node.receivers | mergeOverwrite $receivers | toYaml | nindent 6 }}
    processors: {{ .Values.collectors.node.processors | toYaml | nindent 6 }}
    {{- $basic_auth_extensions := include "basic_auth_extensions" . | fromYaml }}
    extensions: {{ .Values.collectors.node.extensions | mergeOverwrite $basic_auth_extensions | toYaml | nindent 6 }}
    {{- $exporters := include "node_exporters" (dict "kof" .Values.kof) | fromYaml }}
    exporters: {{ .Values.collectors.node.exporters | mergeOverwrite $exporters | toYaml | nindent 6 }}
    {{- $service := include "service" . | fromYaml }}
    service: {{.Values.collectors.node.service | mergeOverwrite $service | toYaml | nindent 6 }}
{{- end }}
