{{- if .Values.jaeger.enabled }}
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: {{ .Release.Name }}-jaeger
  namespace: {{ .Release.Namespace }}
spec:
  strategy: production
  allInOne:
    labels: 
      {{- toYaml .Values.jaeger.collector.podLabels | nindent 6 }}
  collector:
    labels:
      {{- toYaml .Values.jaeger.collector.podLabels | nindent 6 }}
    replicas: {{ .Values.jaeger.collector.replicaCount | default 3 }}
  storage:
{{ toYaml .Values.jaeger.storage | indent 4 }}
  ingress:
    enabled: false
{{- end }}
