{{- if .Values.rootCA.enabled }}
---
apiVersion: config.projectsveltos.io/v1beta1
kind: ClusterProfile
metadata:
  name: {{ .Release.Name }}-child
spec:
  clusterSelector:
    matchLabels:
      k0rdent.mirantis.com/kof-cluster-role: child
      k0rdent.mirantis.com/istio-role: child

  dependsOn:
    - {{ .Release.Name }}-namespaces
    - {{ .Release.Name }}-network

  templateResourceRefs:
    - identifier: ChildConfig
      resource:
        apiVersion: v1
        kind: ConfigMap
        name: kof-cluster-config-{{`{{ .Cluster.metadata.name }}`}}
        namespace: {{ .Values.kcm.namespace }}

  helmCharts:

    - repositoryName:   {{ .Values.kcm.kof.repo.name }}
      repositoryURL:    {{ .Values.kcm.kof.repo.spec.url }}
      {{- include "repo_chart_name" (dict "name" "kof-operators" "type" .Values.kcm.kof.repo.spec.type "repo" .Values.kcm.kof.repo.name) | nindent 6 }}
      chartVersion:     {{ .Chart.Version }}
      releaseName:      kof-operators
      releaseNamespace: {{ .Values.kof.namespace }}
      helmChartAction:  Install

    - repositoryName:   {{ .Values.kcm.kof.repo.name }}
      repositoryURL:    {{ .Values.kcm.kof.repo.spec.url }}
      {{- include "repo_chart_name" (dict "name" "kof-collectors" "type" .Values.kcm.kof.repo.spec.type "repo" .Values.kcm.kof.repo.name) | nindent 6 }}
      chartVersion:     {{ .Chart.Version }}
      releaseName:      kof-collectors
      releaseNamespace: {{ .Values.kof.namespace }}
      helmChartAction:  Install
      values: |
        {{`{{ $patch := index .Cluster.metadata.annotations "k0rdent.mirantis.com/kof-collectors-values" | default "{}" | fromYaml }}`}}
        {{`{{ $childClusterName := .Cluster.metadata.name }}`}}
        {{`{{ $regionalClusterName := getField "ChildConfig" "data.regional_cluster_name" }}`}}
        {{`{{ $collectorsValues := `}}`
        {{ .Values.collectors | toYaml }}
        ` | fromYaml {{`}}`}}
        {{`{{ $values := printf `}}`{{`
        global:
          clusterName: %q
        kof:
          logs:
            endpoint: http://%s-logs:9428/insert/opentelemetry/v1/logs
          metrics:
            endpoint: http://%s-vminsert:8480/insert/0/prometheus/api/v1/write
          traces:
            endpoint: http://%s-jaeger-collector:4318
          basic_auth: false
        opencost:
          enabled: true
          opencost:
            prometheus:
              existingSecretName: ""
              external:
                url: http://%s-vmselect:8481/select/0/prometheus
            exporter:
              defaultClusterId: %q
          `}}`{{` $childClusterName $regionalClusterName $regionalClusterName $regionalClusterName $regionalClusterName $childClusterName | fromYaml }}`}}
        {{`{{ mergeOverwrite $values $collectorsValues $patch | toYaml | nindent 4 }}`}}
{{- end }}
