apiVersion: config.projectsveltos.io/v1beta1
kind: ClusterProfile
metadata:
  name: kof-child-cluster
spec:
  clusterSelector:
    matchLabels:
      k0rdent.mirantis.com/kof-cluster-role: child
    matchExpressions:
      - { key: "k0rdent.mirantis.com/istio-role", operator: DoesNotExist }

  templateResourceRefs:
    - identifier: ChildConfig
      resource:
        apiVersion: v1
        kind: ConfigMap
        name: kof-cluster-config-{{`{{ .Cluster.metadata.name }}`}}
        namespace: {{ .Values.kcm.namespace }}

  helmCharts:
    - repositoryName:   k0rdent-catalog
      repositoryURL:    oci://ghcr.io/k0rdent/catalog/charts
      chartName:        cert-manager
      chartVersion:     1.16.2
      releaseName:      cert-manager
      releaseNamespace: {{ .Release.Namespace }}
      helmChartAction:  Install
      values: |
        cert-manager:
          crds:
            enabled: true

    - repositoryName:   {{ .Values.kcm.kof.repo.name }}
      repositoryURL:    {{ .Values.kcm.kof.repo.url }}
      {{- include "repo_chart_name" (dict "name" "kof-operators" "type" .Values.kcm.kof.repo.type "repo" .Values.kcm.kof.repo.name) | nindent 6 }}
      chartVersion:     {{ .Values.kcm.kof.charts.operators.version }}
      releaseName:      kof-operators
      releaseNamespace: {{ .Release.Namespace }}
      helmChartAction:  Install

    - repositoryName:   {{ .Values.kcm.kof.repo.name }}
      repositoryURL:    {{ .Values.kcm.kof.repo.url }}
      {{- include "repo_chart_name" (dict "name" "kof-collectors" "type" .Values.kcm.kof.repo.type "repo" .Values.kcm.kof.repo.name) | nindent 6 }}
      chartVersion:     {{ .Values.kcm.kof.charts.collectors.version }}
      releaseName:      kof-collectors
      releaseNamespace: {{ .Release.Namespace }}
      helmChartAction:  Install
      values: |
        global:
          clusterName: {{`{{ .Cluster.metadata.name }}`}}
        kof:
          metrics:
            username_key: username
            password_key: password
            credentials_secret_name: storage-vmuser-credentials
            endpoint: {{`{{ getField "ChildConfig" "data.write_metrics_endpoint" }}`}}
          logs:
            username_key: username
            password_key: password
            credentials_secret_name: storage-vmuser-credentials
            endpoint: {{`{{ getField "ChildConfig" "data.write_logs_endpoint" }}`}}
          traces:
            endpoint: {{`{{ getField "ChildConfig" "data.write_traces_endpoint" }}`}}
        opencost:
          enabled: true
          opencost:
            prometheus:
              username_key: username
              password_key: password
              existingSecretName: storage-vmuser-credentials
              external:
                url: {{`{{ getField "ChildConfig" "data.read_metrics_endpoint" }}`}}
            exporter:
              defaultClusterId: {{`{{ .Cluster.metadata.name }}`}}
