# permissions for end users to edit promxyservergroups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: promxy-operator
    app.kubernetes.io/managed-by: kustomize
  name: promxyservergroup-editor-role
rules:
- apiGroups:
  - kof.k0rdent.mirantis.com
  resources:
  - promxyservergroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kof.k0rdent.mirantis.com
  resources:
  - promxyservergroups/status
  verbs:
  - get
