apiVersion: v2
name: kof-istio
description: A Helm chart that deploys Istio with multicluster multinetwork setup
version: "0.3.1"
appVersion: "0.3.1"
dependencies:
  - name: cert-manager-istio-csr
    version: "0.14.0"
    repository: "https://charts.jetstack.io"
  - alias: istiobase
    name: base
    version: "1.24.3"
    repository: "https://istio-release.storage.googleapis.com/charts"
  - name: istiod
    version: "1.24.3"
    repository: "https://istio-release.storage.googleapis.com/charts"
