kcm:
  namespace: kcm-system
  kof:
    # -- Repo of `kof-*` helm charts.
    repo:
      name: kof
      type: oci
      url: oci://ghcr.io/k0rdent/kof/charts
kof:
  namespace: kof
  traces_sampling_percentage: 100
rootCA:
  enabled: true
intermediateCAs:
  mothership:
    certificate: true
    issuer: true
global:
  caAddress: cert-manager-istio-csr.istio-system.svc:443
  meshID: kof
  externalIstiod: true
  multiCluster:
    clusterName: mothership
  network: mothership-network
  meshConfig:
    accessLogFile: /dev/stdout
cert-manager-istio-csr:
  app:
    tls:
      certificateDNSNames:
        - cert-manager-istio-csr.istio-system.svc
    certmanager:
      issuer:
        name: kof-istio-mothership-ca
        kind: Issuer
        group: cert-manager.io
    server:
      clusterID: mothership
istiod:
  extraContainerArgs:
    - --tlsCertFile=/etc/cert-manager/tls/tls.crt
    - --tlsKeyFile=/etc/cert-manager/tls/tls.key
    - --caCertFile=/etc/cert-manager/ca/root-cert.pem
  volumeMounts:
    - mountPath: /etc/cert-manager/tls
      name: cert-manager
      readOnly: true
    - mountPath: /etc/cert-manager/ca
      name: ca-root-cert
      readOnly: true
  volumes:
    - name: cert-manager
      secret:
        defaultMode: 420
        secretName: istiod-tls
    - name: ca-root-cert
      configMap:
        defaultMode: 420
        name: istio-ca-root-cert
        optional: true
  meshConfig:
    enableTracing: true
    extensionProviders:
      - name: otel-tracing
        opentelemetry:
          port: 4317
          service: kof-collectors-node-exporter-collector.kof.svc.cluster.local
          resource_detectors:
            environment: {}
    defaultConfig:
      proxyMetadata:
        ISTIO_META_DNS_CAPTURE: "true"
  env:
    ENABLE_CA_SERVER: false
gateway:
  enabled: false
  name: istio-eastwestgateway
storage: {}
collectors: {}

